
export const search = document.querySelector('.search')
export const city= document.querySelector('.search-input')
export const temp = document.querySelector('.temp')
export const  humidity = document.querySelector('.humidity')
export const wind = document.querySelector('.wind')
export const desc = document.querySelector('.desc')
export const cityName = document.querySelector('.city')
export const icons = document.querySelector('.icon')
export const errors = document.querySelector('.error')
export const converter = document.querySelector('.converter')
export const convert = document.querySelector('.convert')
